### PR TITLE
Update to 23.08 runtime

### PR DESCRIPTION
**Pull request by Justinzobel**

### CODE REVIEW

**Comment by tsdgeos** [comment]
bot, build

**Comment by Justinzobel** [comment]
@g-fb is it suitable to switch Haruna over from an in-manifest build of FFmpeg to the FreeDesktop platform https://github.com/flathub/org.freedesktop.Platform.ffmpeg?

**Comment by g-fb** [comment]
> @g-fb is it suitable to switch Haruna over from an in-manifest build of FFmpeg to the FreeDesktop platform `org.freedesktop.Platform.ffmpeg-full`?

I don't mind, as long as it doesn't break anything.

**Comment by bbhtt** [comment]
You need this patch to fix ffmpeg build https://github.com/flathub/io.github.celluloid_player.Celluloid/commit/6d6d34155dd784f553cddc265204a5caa1bfb8c2 or update it to 6.1 which has it.

**Pull request closed without merging**
