### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by g-fb** [comment]
Closing as I'll release a new version as soon as it's published on the cdn and update runtime with it.

**Comment by travier** [comment]
OK. You could have reused this branch as well as you will likely need: https://github.com/flathub/org.kde.haruna/pull/59/commits/5315dc6f3efa54685bed543d3c99069f4311a9f5

**Comment by g-fb** [comment]
> as you will likely need: [5315dc6](https://github.com/flathub/org.kde.haruna/commit/5315dc6f3efa54685bed543d3c99069f4311a9f5)

Why? It built fine without it https://github.com/flathub/org.kde.haruna/pull/60

**Comment by travier** [comment]
It failed when I run https://github.com/flathub-infra/flatpak-external-data-checker manually on the manifest. But if it works then it's fine.

**Pull request closed without merging**
